"""
配置文件生成模块
将提取的规范数据转换为ARCHICAD插件可用的JSON格式
"""
import json
from pathlib import Path
from typing import Dict
from rich.console import Console
from rich.table import Table
from regulation_extractor import StairRegulation, RegulationRule

console = Console()


class ConfigGenerator:
    """配置文件生成器"""

    @staticmethod
    def regulation_to_dict(regulation: StairRegulation) -> Dict:
        """
        将StairRegulation对象转换为字典

        注意：生成扁平化JSON格式以匹配C++插件的解析逻辑

        Args:
            regulation: 规范对象

        Returns:
            Dict: 字典格式的配置（扁平化结构）
        """

        def rule_to_dict(rule: RegulationRule) -> Dict:
            """转换单个规则"""
            return {
                "min_value": rule.min_value,
                "max_value": rule.max_value,
                "unit": rule.unit,
                "source": rule.source,
                "full_text": rule.full_text
            }

        # 扁平化结构：直接在顶层放置规则（不使用嵌套的"rules"对象）
        config = {
            "regulation_name": regulation.regulation_name,
            "regulation_code": regulation.regulation_code
        }

        if regulation.riser_height:
            config["riser_height"] = rule_to_dict(regulation.riser_height)

        if regulation.tread_depth:
            config["tread_depth"] = rule_to_dict(regulation.tread_depth)

        if regulation.two_r_plus_g:
            config["two_r_plus_g"] = rule_to_dict(regulation.two_r_plus_g)

        if regulation.landing_length:
            config["landing_length"] = rule_to_dict(regulation.landing_length)

        return config

    @staticmethod
    def save_json(regulation: StairRegulation, output_path: str) -> None:
        """
        保存为JSON文件

        Args:
            regulation: 规范对象
            output_path: 输出文件路径
        """
        config = ConfigGenerator.regulation_to_dict(regulation)

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(config, f, ensure_ascii=False, indent=2)

        console.print(f"[green][OK] 配置文件已保存: {output_file}[/green]")

    @staticmethod
    def generate_cpp_header(regulation: StairRegulation, output_path: str) -> None:
        """
        生成C++头文件（可选，方便直接集成到插件）

        Args:
            regulation: 规范对象
            output_path: 输出文件路径
        """
        header_content = f"""// Auto-generated regulation configuration
// Generated from: {regulation.regulation_name} {regulation.regulation_code}
// DO NOT EDIT THIS FILE MANUALLY

#ifndef REGULATION_CONFIG_H
#define REGULATION_CONFIG_H

namespace RegulationConfig {{

    // {regulation.regulation_name} {regulation.regulation_code}

"""

        if regulation.riser_height and regulation.riser_height.max_value:
            header_content += f"""
    // {regulation.riser_height.full_text}
    constexpr double RISER_HEIGHT_MAX = {regulation.riser_height.max_value};  // {regulation.riser_height.unit}
    constexpr const wchar_t* RISER_HEIGHT_SOURCE = L"{regulation.riser_height.source}";
    constexpr const wchar_t* RISER_HEIGHT_TEXT = L"{regulation.riser_height.full_text}";
"""

        if regulation.tread_depth and regulation.tread_depth.min_value:
            header_content += f"""
    // {regulation.tread_depth.full_text}
    constexpr double TREAD_DEPTH_MIN = {regulation.tread_depth.min_value};  // {regulation.tread_depth.unit}
    constexpr const wchar_t* TREAD_DEPTH_SOURCE = L"{regulation.tread_depth.source}";
    constexpr const wchar_t* TREAD_DEPTH_TEXT = L"{regulation.tread_depth.full_text}";
"""

        if regulation.two_r_plus_g:
            if regulation.two_r_plus_g.min_value:
                header_content += f"""
    // {regulation.two_r_plus_g.full_text}
    constexpr double TWO_R_PLUS_G_MIN = {regulation.two_r_plus_g.min_value};  // {regulation.two_r_plus_g.unit}
"""
            if regulation.two_r_plus_g.max_value:
                header_content += f"""    constexpr double TWO_R_PLUS_G_MAX = {regulation.two_r_plus_g.max_value};  // {regulation.two_r_plus_g.unit}
    constexpr const wchar_t* TWO_R_PLUS_G_SOURCE = L"{regulation.two_r_plus_g.source}";
    constexpr const wchar_t* TWO_R_PLUS_G_TEXT = L"{regulation.two_r_plus_g.full_text}";
"""

        if regulation.landing_length and regulation.landing_length.min_value:
            header_content += f"""
    // {regulation.landing_length.full_text}
    constexpr double LANDING_LENGTH_MIN = {regulation.landing_length.min_value};  // {regulation.landing_length.unit}
    constexpr const wchar_t* LANDING_LENGTH_SOURCE = L"{regulation.landing_length.source}";
    constexpr const wchar_t* LANDING_LENGTH_TEXT = L"{regulation.landing_length.full_text}";
"""

        header_content += """
}}  // namespace RegulationConfig

#endif  // REGULATION_CONFIG_H
"""

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(header_content)

        console.print(f"[green][OK] C++头文件已生成: {output_file}[/green]")

    @staticmethod
    def display_summary(regulation: StairRegulation) -> None:
        """
        在终端显示提取结果摘要

        Args:
            regulation: 规范对象
        """
        console.print(f"\n[bold cyan]{'='*60}[/bold cyan]")
        console.print(f"[bold]规范名称:[/bold] {regulation.regulation_name}")
        console.print(f"[bold]规范编号:[/bold] {regulation.regulation_code}")
        console.print(f"[bold cyan]{'='*60}[/bold cyan]\n")

        table = Table(title="提取的规范限制", show_header=True, header_style="bold magenta")
        table.add_column("检查项", style="cyan", width=15)
        table.add_column("限值", style="green", width=15)
        table.add_column("来源", style="yellow", width=15)
        table.add_column("完整条文", style="white", width=50)

        if regulation.riser_height and regulation.riser_height.max_value:
            table.add_row(
                "踏步高度",
                f"≤ {regulation.riser_height.max_value} {regulation.riser_height.unit}",
                regulation.riser_height.source,
                regulation.riser_height.full_text
            )

        if regulation.tread_depth and regulation.tread_depth.min_value:
            table.add_row(
                "踏步宽度",
                f"≥ {regulation.tread_depth.min_value} {regulation.tread_depth.unit}",
                regulation.tread_depth.source,
                regulation.tread_depth.full_text
            )

        if regulation.two_r_plus_g:
            range_text = ""
            if regulation.two_r_plus_g.min_value and regulation.two_r_plus_g.max_value:
                range_text = f"{regulation.two_r_plus_g.min_value}~{regulation.two_r_plus_g.max_value} {regulation.two_r_plus_g.unit}"
            table.add_row(
                "2R+G 公式",
                range_text,
                regulation.two_r_plus_g.source,
                regulation.two_r_plus_g.full_text
            )

        if regulation.landing_length and regulation.landing_length.min_value:
            table.add_row(
                "平台长度",
                f"≥ {regulation.landing_length.min_value} {regulation.landing_length.unit}",
                regulation.landing_length.source,
                regulation.landing_length.full_text
            )

        console.print(table)
        console.print()


if __name__ == "__main__":
    # 测试代码
    from regulation_extractor import StairRegulation, RegulationRule

    test_regulation = StairRegulation(
        regulation_name="住宅建筑规范",
        regulation_code="GB 50368-2005",
        riser_height=RegulationRule(
            max_value=0.175,
            unit="m",
            source="第6.3.2条",
            full_text="楼梯踏步高度不应大于0.175m"
        ),
        tread_depth=RegulationRule(
            min_value=0.26,
            unit="m",
            source="第6.3.2条",
            full_text="踏步宽度不应小于0.26m"
        )
    )

    ConfigGenerator.display_summary(test_regulation)
    ConfigGenerator.save_json(test_regulation, "output/test_config.json")
