#ifndef _RESOURCES_HPP_
#define _RESOURCES_HPP_

#define ID_ADDON_INFO			32000
#define ID_MENU_STRINGS				32500
#define ID_MENU_PROMPT_STRINGS		32520
#define ID_PALETTE_MENU_STRINGS		32540
#define ID_PALETTE_PROMPT_STRINGS	32541

#define ID_MENU_ICON			32000

#define ID_COMPLIANCE_PALETTE	32600
#define ID_COMPLIANCE_SUMMARY	1
#define ID_UPLOAD_PDF_BUTTON	2
#define ID_CHECK_NOW_BUTTON		3
#define ID_REGULATION_LABEL		4
#define ID_REGULATION_INFO_TEXT	5
#define ID_COMPLIANCE_LISTBOX	7
#define ID_COMPLIANCE_STRINGS	32610


#endif //_RESOURCES_HPP_
